var width = 10;
var height = 20;
var area = width * height;
console.log('The Value of Area is: ', area);
console.log('The typeof area is: ', typeof area);
var bill = 15;
var payment = 20;
var change = payment - bill;
console.log('The value of change is: ', change);
console.log('The typeof change is: ', typeof change);
var firstName = 'Daniel';
var lastName = 'Rosenbaum';
var fullName = firstName + ' ' + lastName;
console.log('My full name is: ', fullName);
console.log('The typeof fullName is: ', typeof fullName);
var ph = 25;
var isAcidic = ph < 7;
console.log('Is ph acidic? ', isAcidic);
console.log('The typeof isAcidic is: ', typeof isAcidic);
var headCount = 50;
var isSparta = headCount === 300;
console.log('Is the head count Sparta? ', isSparta);
console.log('The typeof isSparta is: ', typeof isSparta);
var motto = fullName;
motto = motto + ' ' + 'is the GOAT';
console.log('The value of motto is: ', motto);
console.log('The typeof motto is: ', typeof motto);
