const fullName = 'Daniel Rosenbaum';
const isCool = true;
const totalPets = 1;
console.log('Name: ', fullName);
console.log('type of fullname: ', typeof fullName);
console.log('Are they cool? ', isCool);
console.log('typeof isCool: ', typeof isCool);
console.log('Number of Pets: ', totalPets);
console.log('typeof totalPets: ', typeof totalPets);
const unknown = null;
console.log('What is an unknown? ', unknown);
console.log('typeof unknown: ', typeof unknown);
let never;
console.log('What is never?', never);
console.log('typeof never: ', typeof never);
