var fullName = 'Daniel Rosenbaum';
var isCool = true;
var totalPets = 1;
console.log('Name: ', fullName);
console.log('type of fullname: ', typeof fullName);
console.log('Are they cool? ', isCool);
console.log('typeof isCool: ', typeof isCool);
console.log('Number of Pets: ', totalPets);
console.log('typeof totalPets: ', typeof totalPets);
var unknown = null;
console.log('What is an unknown? ', unknown);
console.log('typeof unknown: ', typeof unknown);
var never;
console.log('What is never? ', never);
console.log('typeof never:', typeof never);
